$(function(){
	
	$("#loginform").validate(
	{
		rules:{
			user:{
				required:true,
			},
			pass:{
                required:true,
             	rangelength:[6,12]
            },
		},
		message:{
			user:"请输入名字",
			pass:{
				required:"请输入密码",
				minlength:$.validator.format("密码不能小于{0}个字符")
			},
		},
		errorElement:"div",
		errorPlacement:function(error,val){
			if($("b").next('b')){
				error.css("color","red").insertBefore(val.parent());
			}
		},
		success:function(success,val){
			if($(val).next('i').length==0){
				$("<i>").css({"width":"10px","height":"10px","borderRadius":"50%","background":"red"}).insertBefore(val);
			}
			console.log($("i"));
		}
	}
	)
	$("#login").on("click",function(){
		$("#loginform").submit();
	})
})
$.validator.setDefaults({
	submitHandler:function(){
		alert("登录成功");

	}
})
